name: Weekly Coupon Update
on:
  schedule:
    - cron: '0 0 */7 * *' # Every 7 days
  workflow_dispatch: # Allow manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm install axios cheerio @supercharge/promise-pool
      
      - name: Run Scraper
        run: node scraper.js
      
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update coupon data" || echo "No changes"
          git push
